### ISSUE TITLE
MIT license?

### ISSUE THREAD

**Issue by tdb-alcorn** [lucasb-eyer/flex-bison-indentation#1]
Lucas, thanks for creating this example, it has helped me greatly. I'm hoping to use your code with my own modifications in a closed-source project: is that ok with you? If you were hoping to allow anyone to use this example for any purpose, would you consider including an MIT license in the repo?

**Comment by lucasb-eyer** [comment]
Thank you so much for asking and not just taking it! Yes, I am fine with including an MIT license, and I am happy that this was useful for you :)

**Comment by tdb-alcorn** [comment]
Thanks again!
